image: rocker/tidyverse:latest

pipelines:
  default:
    - step:
        script:
          - cd /opt/atlassian/pipelines/agent/build          
          - Rscript -e 'devtools::build()'
          - Rscript -e 'devtools::install(upgrade_dependencies = FALSE, build_vignettes = FALSE)'
          - Rscript -e 'devtools::check()'